# Generated by Django 5.2.16 on 2026-07-24 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta', models.CharField(blank=True, max_length=150)),
                ('propietario', models.CharField(blank=True, max_length=150)),
                ('direccion', models.CharField(blank=True, max_length=300)),
                ('fecha', models.DateTimeField()),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dolar_valor', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PersonaGanancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'persona de ganancia',
                'verbose_name_plural': 'personas de ganancia',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'tipo de pago',
                'verbose_name_plural': 'tipos de pago',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'tipo de producto',
                'verbose_name_plural': 'tipos de producto',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_seguimiento', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('entregado', models.BooleanField(default=False)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paquetes', to='negocio.pedido')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('link', models.URLField(blank=True, max_length=500)),
                ('foto', models.URLField(blank=True, max_length=500)),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='negocio.marca')),
                ('tipo_producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='negocio.tipoproducto')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='InventarioLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_inicial', models.PositiveIntegerField()),
                ('costo_unitario_dolar', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('costo_unitario_soles', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo_soles_manual', models.BooleanField(default=True)),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='negocio.paquete')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='negocio.producto')),
            ],
            options={
                'verbose_name': 'lote de inventario',
                'verbose_name_plural': 'lotes de inventario',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('direccion_entrega', models.CharField(blank=True, max_length=300)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pagado', models.BooleanField(default=False)),
                ('estado_entrega', models.CharField(max_length=50)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='negocio.cliente')),
                ('tipo_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='negocio.tipopago')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario_venta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_venta', to='negocio.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='negocio.venta')),
            ],
            options={
                'verbose_name': 'detalle de venta',
                'verbose_name_plural': 'detalles de venta',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SalidaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('detalle_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salidas', to='negocio.detalleventa')),
                ('inventario_lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salidas', to='negocio.inventariolote')),
            ],
            options={
                'verbose_name': 'salida de inventario',
                'verbose_name_plural': 'salidas de inventario',
                'constraints': [models.UniqueConstraint(fields=('detalle_venta', 'inventario_lote'), name='salida_detalle_lote_unica')],
            },
        ),
        migrations.CreateModel(
            name='DistribucionGanancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pagado', models.BooleanField(default=False)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distribuciones', to='negocio.personaganancia')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribuciones', to='negocio.venta')),
            ],
            options={
                'verbose_name': 'distribución de ganancia',
                'verbose_name_plural': 'distribuciones de ganancia',
                'ordering': ['persona__nombre'],
                'constraints': [models.UniqueConstraint(fields=('venta', 'persona'), name='distribucion_venta_persona_unica')],
            },
        ),
    ]
