# Generated by Django 5.2.16 on 2026-07-24 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0002_alter_producto_foto'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='distribucionganancia',
            name='distribucion_venta_persona_unica',
        ),
        migrations.AddField(
            model_name='distribucionganancia',
            name='detalle_venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distribuciones_ganancia', to='negocio.detalleventa'),
        ),
        migrations.AddConstraint(
            model_name='distribucionganancia',
            constraint=models.UniqueConstraint(fields=('detalle_venta', 'persona'), name='distribucion_detalle_persona_unica'),
        ),
    ]
